### ISSUE TITLE
MySQL Dependency

### ISSUE THREAD

**Issue by bgmike** [IBM-Swift/SwiftKueryMySQL#63]
Greetings

I'm quite new to Swift and I'm slowly learning how stuff works.

I was following the tutorials on [https://www.kitura.io/docs/getting-started/hello-world.html](https://www.kitura.io/docs/getting-started/hello-world.html) and I encountered some issues when I got to the Databases section.

In short, the difficulty was that the project could not build after I added the `SwiftKueryMySQL` dependency. Eventually I figured out that the reason for this is because I do not have MySQL installed on my computer. This is intentional. I prefer to run things like databases in docker containers rather than having them installed on the host.

 So is there a way to proceed without having to install MySQL locally?

**Comment by kilnerm** [comment]
@bgmike If you want to run your MySQL instance in a container you can do so and simply update the MySQL Connections with the necessary network address etc....

If you want to use the plugin to develop locally you will need to install the mysqlclient library and pkg-config. Without these your application will not be able to build or link properly.

You could use a container for development and edit the source within it remotely. I haven't ever tried this but it should work fine.

**Comment by cflexible** [comment]
Hello,
it is very time-robbing to create a first kueryMySQL project. Please add an installation guide for a normal scenario;)
This is what I mean: In normal cases I like to have a separate DB server and I want to have my system as clean as possible. Therefor I installed my MySQL database from the Oracle download. With this I could find the include and lib directories which are necessary for using Kuery. Instead of installing them in a /usr/local whatever directory on my development machine I add those directories to my project in XCode.
![Bildschirmfoto 2019-07-13 um 04 06 02](https://user-images.githubusercontent.com/52855106/61170829-0f68f380-a56f-11e9-915f-d68c314d2c62.png)
The next step was to find out how to include that in the XCode compile process. So you have to add the following entries in the Build settings:
$SRCROOT/MySQL/include in Header Search Paths
$SRCROOT/MySQL/lib in Library Search Paths
The next step is to include the kuery into the package: I use these entries in the dependencies, so I don't need to download them manually and they are in my project:
       .package(url: "https://github.com/IBM-Swift/Kitura", from: "2.7.1"),
       .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMajor(from: "1.8.1")),
       .package(url: "https://github.com/IBM-Swift/Swift-Kuery.git", .upToNextMajor(from: "3.0.1")),
       .package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL", .upToNextMajor(from: "2.0.2"))

Now I ran into last two problems which I wasn't able to fix.
1. I got a compiler error that **mysqlclient** can't be find. Here is the first question. What is the different of installing mysql with Homebrew and from Oracle? I think somewhere must the mysqlclient be definied but I wasn't able to find an information about that.
2. The second problem is "**dyld: Library not loaded: libssl.1.0.0.dylib**" in XCode while the run on console works the run with XCode doesn't. What must be done to fix that?

It would be great to get solutions for the problems.

Thank

**Comment by kilnerm** [comment]
@cflexible, Do you have the `libmysqlclient` libraries on your machine? When installed via brew they will be automatically symlinked from `/usr/local/lib`.

If the libraries are present you will need to set the header and library search paths in Xcode. If you look in the root of the SwiftKueryMySQL source tree you will find a file named `Config.xcconfig`. This file can be used to generate and Xcode project with the correct build settings for a system configured according to the Readme. You can edit the paths in this file to suit your needs and use it to generate your Xcode project using `swift package generate-xcodeproj --xcconfig-overrides Config.xcconfig`.

The second error suggests that you do not have openssl installed or configured correctly. Could you check to see if you have installed openssl? (brew list will show you all installed formula if you use homebrew).

**Comment by djones6** [comment]
Closing on the assumption that @kilnerm's response above helped you resolve the problem, however please re-open if you are still having trouble, or reach out on Slack.
